### PR TITLE
Update the logo

### PR DESCRIPTION
**Pull request by OrnitOnGithub**
I prefer it this way :)

### CODE REVIEW

**Comment by AurelienJt** [comment]
👍 We'll vote in class.

**Comment by 0rangeFruit** [comment]
I agree

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Review by ErdaBerda — COMMENTED** [review]
Celui la est nice

**Comment by 0rangeFruit** [comment]
I prefer Ornits way honestly

**Comment by OrnitOnGithub** [comment]
very demure

**Pull request merged**
